// Location data mapping - maps location titles to folder names and details
export const locationData: Record<string, {
  folder: string;
  title: string;
  description: string;
  location: string;
  climate: string;
  features: string[];
  detailedDescription?: string;
  nearbyAttractions?: string[];
  bestTimeToVisit?: string;
  activities?: string[];
  amenities?: string[];
  propertyDetails?: {
    size?: string;
    capacity?: string;
    bedrooms?: string;
    bathrooms?: string;
  };
  transportation?: string;
  localCulture?: string;
}> = {
  "monteverde-retreat": {
    folder: "main/domy/d6",
    title: "Monteverde Retreat",
    description: "Immerse yourself in biodiversity. Our eco-domes are inspired by the rich flora, offering an unparalleled sustainable living experience in the heart of Costa Rica's cloud forest.",
    location: "Monteverde, Costa Rica",
    climate: "Tropical Climate",
    features: [
      "Cloud forest integration",
      "Biodiversity preservation",
      "Sustainable tourism focus",
    ],
    detailedDescription: "Nestled in the heart of Costa Rica's famous Monteverde Cloud Forest Reserve, our eco-domes offer a unique opportunity to live in harmony with one of the world's most biodiverse ecosystems. The area is home to over 2,500 plant species, 400 bird species, and countless mammals, making it a paradise for nature enthusiasts. The cool, misty climate creates an otherworldly atmosphere where you'll wake up to the sounds of howler monkeys and colorful toucans.",
    nearbyAttractions: [
      "Monteverde Cloud Forest Biological Reserve",
      "Santa Elena Cloud Forest Reserve",
      "Selvatura Adventure Park",
      "Monteverde Butterfly Garden",
      "Coffee Plantation Tours",
      "Canopy Zipline Tours",
      "Hummingbird Gallery",
    ],
    bestTimeToVisit: "December to April (dry season) or May to November (green season with lush vegetation)",
    activities: [
      "Bird watching and wildlife spotting",
      "Hiking through cloud forest trails",
      "Canopy tours and ziplining",
      "Coffee and chocolate plantation tours",
      "Night walks to see nocturnal wildlife",
      "Photography and nature observation",
    ],
    amenities: [
      "Solar-powered energy systems",
      "Rainwater collection and filtration",
      "Organic garden spaces",
      "Wildlife observation decks",
      "Eco-friendly waste management",
      "High-speed internet connectivity",
    ],
    propertyDetails: {
      size: "1,200 - 2,000 sq ft",
      capacity: "4-6 people",
      bedrooms: "2-3 bedrooms",
      bathrooms: "2 bathrooms",
    },
    transportation: "Monteverde is accessible by car from San José (3-4 hours) or Liberia Airport (2.5 hours). Local transportation includes taxis, shuttles, and rental cars. The area is walkable with many attractions within walking distance.",
    localCulture: "Monteverde was founded by Quaker settlers in the 1950s, creating a unique blend of Costa Rican and Quaker culture. The community is deeply committed to conservation and sustainable living. You'll find excellent local restaurants, artisan shops, and a welcoming international community.",
  },
  "adriatic-haven": {
    folder: "main/domy/d7",
    title: "Adriatic Haven",
    description: "Perched on the stunning Adriatic coastline, these domes are designed for sea breezes and historic cultural sites. Experience the perfect blend of luxury and Mediterranean charm.",
    location: "Dubrovnik, Croatia",
    climate: "Mediterranean Climate",
    features: [
      "Adriatic sea views",
      "Historic site proximity",
      "Mediterranean architecture",
    ],
    detailedDescription: "Experience the magic of the Croatian Adriatic coast from our stunning eco-dome community near Dubrovnik. Known as the 'Pearl of the Adriatic,' this UNESCO World Heritage site offers a perfect blend of historic charm and natural beauty. Our domes are strategically positioned to capture the famous sea breezes while providing breathtaking views of the crystal-clear Adriatic waters and the historic city walls.",
    nearbyAttractions: [
      "Dubrovnik Old Town (UNESCO World Heritage)",
      "Lokrum Island Nature Reserve",
      "Mount Srđ with panoramic views",
      "Elafiti Islands",
      "Cavtat - historic coastal town",
      "Pelješac Peninsula wine region",
      "Ston - famous for its walls and oysters",
    ],
    bestTimeToVisit: "May to September for warm weather and swimming, or April and October for fewer crowds and pleasant temperatures",
    activities: [
      "Swimming and water sports in the Adriatic",
      "Exploring historic Dubrovnik Old Town",
      "Island hopping to nearby islands",
      "Wine tasting in local vineyards",
      "Hiking along coastal trails",
      "Boat tours and sailing",
      "Cultural festivals and events",
    ],
    amenities: [
      "Private beach access",
      "Solar power with battery backup",
      "Seawater desalination system",
      "Outdoor terraces with sea views",
      "Modern kitchen facilities",
      "Air conditioning and heating",
    ],
    propertyDetails: {
      size: "1,500 - 2,500 sq ft",
      capacity: "4-8 people",
      bedrooms: "2-4 bedrooms",
      bathrooms: "2-3 bathrooms",
    },
    transportation: "Dubrovnik Airport is 20 km away with international connections. The city center is easily accessible by car, bus, or boat. Public transportation is excellent, and many areas are walkable. Ferry connections to nearby islands are frequent.",
    localCulture: "Dubrovnik boasts a rich history dating back to the 7th century. The city's Renaissance architecture, stunning fortifications, and vibrant cultural scene make it a world-class destination. Enjoy fresh Mediterranean cuisine, local wines, and the famous Croatian hospitality.",
  },
  "algarve-coastal-village": {
    folder: "main/domy/d8",
    title: "Algarve Coastal Village",
    description: "Beachfront eco-village with sustainable living and direct access to golden sand beaches and the crystal blue waters of Portugal's famous Algarve region.",
    location: "Lagos, Portugal",
    climate: "Mediterranean Climate",
    features: [
      "Beachfront access",
      "Algarve region charm",
      "Coastal village lifestyle",
    ],
    detailedDescription: "Discover the beauty of Portugal's Algarve region from our beachfront eco-dome community in Lagos. This stunning coastal area is famous for its dramatic cliffs, golden beaches, and crystal-clear waters. Our domes offer direct access to some of Europe's most beautiful beaches, where you can enjoy world-class surfing, swimming, and water sports. The charming town of Lagos combines historic Portuguese architecture with a vibrant modern lifestyle.",
    nearbyAttractions: [
      "Praia Dona Ana - stunning beach with rock formations",
      "Pont da Piedade - dramatic sea caves and grottoes",
      "Lagos Old Town with historic walls",
      "Sagres - surfing capital and historic fort",
      "Cape St. Vincent - most southwestern point of Europe",
      "Benagil Sea Cave - famous natural wonder",
      "Zoomarine theme park",
    ],
    bestTimeToVisit: "April to October for beach weather, with July and August being peak season. Spring and fall offer perfect temperatures with fewer crowds.",
    activities: [
      "Surfing and paddleboarding",
      "Beach hopping along the coast",
      "Boat tours to sea caves",
      "Hiking along coastal cliffs",
      "Golfing at world-class courses",
      "Wine tasting in local vineyards",
      "Exploring historic towns",
    ],
    amenities: [
      "Direct beach access",
      "Solar power systems",
      "Rainwater harvesting",
      "Outdoor shower and changing areas",
      "Beach equipment storage",
      "BBQ and outdoor dining areas",
    ],
    propertyDetails: {
      size: "1,400 - 2,200 sq ft",
      capacity: "4-6 people",
      bedrooms: "2-3 bedrooms",
      bathrooms: "2 bathrooms",
    },
    transportation: "Faro Airport is 90 km away with international flights. Lagos is well-connected by train and bus. The town is very walkable, and bike rentals are popular. Car rentals are recommended for exploring the region.",
    localCulture: "The Algarve offers a relaxed Mediterranean lifestyle with excellent cuisine, friendly locals, and a strong expat community. Lagos combines traditional Portuguese culture with modern amenities. Enjoy fresh seafood, local wines, and the famous Portuguese hospitality in a stunning coastal setting.",
  },
  "bolu": {
    folder: "bolu",
    title: "Bolu Location",
    description: "Discover our eco-dome community in Bolu, featuring stunning natural landscapes and sustainable living solutions.",
    location: "Bolu, Turkey",
    climate: "Continental Climate",
    features: [
      "Mountain views",
      "Natural landscapes",
      "Sustainable living",
    ],
    detailedDescription: "Nestled in the beautiful Bolu province, our eco-dome community offers a peaceful retreat surrounded by lush forests, pristine lakes, and majestic mountains. Bolu is known for its natural beauty, clean air, and tranquil atmosphere, making it perfect for those seeking a sustainable lifestyle away from the hustle of city life. The area is rich in natural springs, hiking trails, and traditional Turkish culture.",
    nearbyAttractions: [
      "Abant Lake - stunning mountain lake",
      "Yedigöller National Park - seven beautiful lakes",
      "Kartalkaya Ski Resort",
      "Gölcük Nature Park",
      "Bolu Museum",
      "Traditional Turkish villages",
      "Natural hot springs",
    ],
    bestTimeToVisit: "Year-round destination. Summer (June-August) for hiking and lakes, winter (December-March) for skiing, spring and fall for mild weather and beautiful colors.",
    activities: [
      "Hiking and trekking",
      "Skiing and winter sports",
      "Fishing in mountain lakes",
      "Photography and nature observation",
      "Mountain biking",
      "Camping and picnicking",
      "Exploring traditional Turkish culture",
    ],
    amenities: [
      "Mountain view terraces",
      "Solar power systems",
      "Natural spring water access",
      "Fireplace for winter",
      "Outdoor BBQ areas",
      "Storage for sports equipment",
    ],
    propertyDetails: {
      size: "1,200 - 2,000 sq ft",
      capacity: "4-6 people",
      bedrooms: "2-3 bedrooms",
      bathrooms: "2 bathrooms",
    },
    transportation: "Bolu is easily accessible from Istanbul (3 hours) and Ankara (2 hours) by car. The city has good road connections. Local transportation includes buses and taxis. Car rental is recommended for exploring the natural areas.",
    localCulture: "Bolu is known for its traditional Turkish hospitality and rich cultural heritage. The region is famous for its cuisine, particularly dairy products and local specialties. Experience authentic Turkish village life while enjoying modern amenities in a stunning natural setting.",
  },
  "fethiye": {
    folder: "fethiye",
    title: "Fethiye Location",
    description: "Experience coastal living in Fethiye with our eco-dome homes designed for the Mediterranean lifestyle.",
    location: "Fethiye, Turkey",
    climate: "Mediterranean Climate",
    features: [
      "Coastal access",
      "Mediterranean lifestyle",
      "Stunning sea views",
    ],
    detailedDescription: "Fethiye is one of Turkey's most beautiful coastal destinations, offering a perfect blend of stunning natural beauty, rich history, and modern amenities. Our eco-domes are positioned to take advantage of the famous Turkish Riviera's crystal-clear waters, beautiful beaches, and dramatic mountain backdrop. The area is known for its blue cruise routes, ancient Lycian ruins, and vibrant marina life.",
    nearbyAttractions: [
      "Ölüdeniz Beach - world-famous blue lagoon",
      "Saklıkent Gorge - stunning canyon",
      "Kayaköy - abandoned Greek village",
      "Butterfly Valley - secluded beach paradise",
      "Lycian Rock Tombs",
      "Fethiye Marina and Old Town",
      "Tlos Ancient City",
    ],
    bestTimeToVisit: "April to October for beach weather and water activities. May-June and September-October offer perfect temperatures with fewer crowds.",
    activities: [
      "Blue cruise sailing trips",
      "Paragliding from Babadağ Mountain",
      "Scuba diving and snorkeling",
      "Beach hopping and swimming",
      "Hiking the Lycian Way",
      "Exploring ancient ruins",
      "Water sports and boat tours",
    ],
    amenities: [
      "Sea view terraces",
      "Solar power with battery backup",
      "Outdoor shower areas",
      "Boat docking facilities nearby",
      "Modern kitchen facilities",
      "Air conditioning",
    ],
    propertyDetails: {
      size: "1,500 - 2,400 sq ft",
      capacity: "4-8 people",
      bedrooms: "2-4 bedrooms",
      bathrooms: "2-3 bathrooms",
    },
    transportation: "Dalaman Airport is 50 km away with international flights. Fethiye is well-connected by bus and has a good local transportation system. The town is walkable, and boat taxis are available to nearby beaches.",
    localCulture: "Fethiye combines traditional Turkish culture with a modern, international vibe. The area has a large expat community and offers excellent restaurants, cafes, and nightlife. Experience authentic Turkish cuisine, local markets, and the famous Turkish hospitality in a stunning coastal setting.",
  },
  "marmaris": {
    folder: "marmaris",
    title: "Marmaris Location",
    description: "Luxury eco-dome living in Marmaris, combining sustainable design with coastal beauty.",
    location: "Marmaris, Turkey",
    climate: "Mediterranean Climate",
    features: [
      "Luxury coastal living",
      "Sustainable design",
      "Mediterranean beauty",
    ],
    detailedDescription: "Marmaris is one of Turkey's premier coastal destinations, offering luxury living in a stunning natural setting. Our eco-domes combine sustainable design with premium amenities, positioned to enjoy the beautiful Mediterranean coastline, pine-clad mountains, and world-class marina. The area is known for its vibrant nightlife, excellent restaurants, and beautiful beaches.",
    nearbyAttractions: [
      "Marmaris Castle and Old Town",
      "Cleopatra Island (Sedir Island)",
      "Dalyan and Iztuzu Beach (turtle nesting)",
      "Marmaris National Park",
      "Turunç - peaceful coastal village",
      "Kumlubük Bay",
      "Marmaris Marina",
    ],
    bestTimeToVisit: "May to October for beach weather. July and August are peak season. April, May, September, and October offer ideal weather with fewer crowds.",
    activities: [
      "Yacht and boat tours",
      "Scuba diving and water sports",
      "Beach activities and swimming",
      "Hiking in pine forests",
      "Exploring historic sites",
      "Shopping in local markets",
      "Nightlife and entertainment",
    ],
    amenities: [
      "Luxury finishes and design",
      "Private beach access",
      "Solar power systems",
      "Marina proximity",
      "Infinity pool areas",
      "Premium kitchen and appliances",
    ],
    propertyDetails: {
      size: "1,800 - 3,000 sq ft",
      capacity: "6-10 people",
      bedrooms: "3-5 bedrooms",
      bathrooms: "3-4 bathrooms",
    },
    transportation: "Dalaman Airport is 90 km away. Marmaris has excellent road connections and a good local bus system. The town center and marina are walkable, and water taxis connect to nearby beaches.",
    localCulture: "Marmaris offers a sophisticated coastal lifestyle with excellent dining, shopping, and entertainment options. The area attracts both Turkish and international visitors, creating a vibrant, cosmopolitan atmosphere while maintaining authentic Turkish charm.",
  },
  "canakkale": {
    folder: "canakkale",
    title: "Çanakkale Location",
    description: "Historic and beautiful Çanakkale offers unique eco-dome living experiences.",
    location: "Çanakkale, Turkey",
    climate: "Mediterranean Climate",
    features: [
      "Historic significance",
      "Coastal location",
      "Unique living experience",
    ],
    detailedDescription: "Çanakkale is a city rich in history and natural beauty, strategically located on the Dardanelles Strait. Our eco-domes offer a unique opportunity to live in an area of immense historical significance, from ancient Troy to the Gallipoli battlefields. The city combines coastal charm with cultural richness, offering stunning views of the strait and easy access to both European and Asian sides of Turkey.",
    nearbyAttractions: [
      "Ancient Troy archaeological site",
      "Gallipoli Peninsula Historical National Park",
      "Çanakkale Clock Tower",
      "Troy Museum",
      "Assos Ancient City",
      "Bozcaada Island",
      "Gökçeada Island",
    ],
    bestTimeToVisit: "April to October for pleasant weather. Spring and fall are ideal for exploring historical sites. Summer offers beach weather and island visits.",
    activities: [
      "Exploring ancient archaeological sites",
      "Historical tours and museums",
      "Island hopping to Bozcaada and Gökçeada",
      "Wine tasting on islands",
      "Coastal walks and hiking",
      "Fishing and water activities",
      "Cultural festivals and events",
    ],
    amenities: [
      "Historic area proximity",
      "Solar power systems",
      "Coastal view terraces",
      "Cultural center access",
      "Modern amenities",
      "Secure parking",
    ],
    propertyDetails: {
      size: "1,300 - 2,100 sq ft",
      capacity: "4-6 people",
      bedrooms: "2-3 bedrooms",
      bathrooms: "2 bathrooms",
    },
    transportation: "Çanakkale Airport has domestic flights. The city is well-connected by bus and ferry. Car rental is recommended for exploring historical sites. Ferry connections to islands are regular.",
    localCulture: "Çanakkale is a university town with a vibrant cultural scene. The area is rich in history, from ancient civilizations to World War I. Experience authentic Turkish culture, excellent local cuisine, and the unique position between Europe and Asia.",
  },
  "kocaeli": {
    folder: "kocaeli",
    title: "Kocaeli Location",
    description: "Modern eco-dome communities in Kocaeli, blending urban convenience with natural beauty.",
    location: "Kocaeli, Turkey",
    climate: "Continental Climate",
    features: [
      "Urban convenience",
      "Natural beauty",
      "Modern communities",
    ],
    detailedDescription: "Kocaeli offers the perfect balance between urban convenience and natural beauty. Located between Istanbul and the Black Sea coast, our eco-dome community provides easy access to major cities while maintaining a peaceful, nature-focused lifestyle. The area features beautiful forests, lakes, and parks, combined with modern infrastructure and excellent connectivity.",
    nearbyAttractions: [
      "Sapanca Lake - beautiful mountain lake",
      "Maşukiye - forest and waterfall area",
      "Kartepe Ski Resort",
      "Kocaeli Science Center",
      "SEKA Paper Museum",
      "Osman Hamdi Bey Museum",
      "Ballıkayalar Nature Park",
    ],
    bestTimeToVisit: "Year-round destination. Summer for lake activities, winter for skiing, spring and fall for hiking and nature activities.",
    activities: [
      "Hiking and nature walks",
      "Skiing and winter sports",
      "Lake activities and fishing",
      "Mountain biking",
      "Exploring museums and culture",
      "Shopping and dining",
      "Day trips to Istanbul",
    ],
    amenities: [
      "Urban connectivity",
      "Solar power systems",
      "Modern infrastructure",
      "High-speed internet",
      "Community facilities",
      "Easy access to services",
    ],
    propertyDetails: {
      size: "1,400 - 2,200 sq ft",
      capacity: "4-6 people",
      bedrooms: "2-3 bedrooms",
      bathrooms: "2 bathrooms",
    },
    transportation: "Excellent transportation links. Sabiha Gökçen Airport is 45 minutes away. High-speed train connections to Istanbul. Good local bus and taxi services. Car rental available.",
    localCulture: "Kocaeli combines modern Turkish urban life with natural beauty. The area has a growing expat community and offers excellent schools, healthcare, and shopping. Experience the best of both worlds - city convenience and natural tranquility.",
  },
  "atlas": {
    folder: "atlas",
    title: "Atlas Location",
    description: "Discover our eco-dome projects in the Atlas region, featuring unique architectural designs.",
    location: "Atlas Region",
    climate: "Continental Climate",
    features: [
      "Unique architecture",
      "Mountain landscapes",
      "Sustainable design",
    ],
    detailedDescription: "The Atlas region offers a unique opportunity to experience sustainable living in a dramatic mountain setting. Our eco-domes are designed to blend seamlessly with the rugged mountain landscape while providing modern comfort and luxury. The area is known for its stunning vistas, clean mountain air, and opportunities for outdoor adventure.",
    nearbyAttractions: [
      "Mountain hiking trails",
      "Scenic viewpoints",
      "Natural springs",
      "Traditional villages",
      "Wildlife observation areas",
      "Photography spots",
      "Adventure sports facilities",
    ],
    bestTimeToVisit: "Year-round destination. Summer for hiking and outdoor activities, winter for snow sports and cozy mountain living, spring and fall for mild weather and beautiful scenery.",
    activities: [
      "Mountain hiking and trekking",
      "Rock climbing",
      "Mountain biking",
      "Photography",
      "Wildlife observation",
      "Stargazing",
      "Adventure sports",
    ],
    amenities: [
      "Mountain view terraces",
      "Solar power systems",
      "Mountain water access",
      "Fireplace and heating",
      "Outdoor activity storage",
      "Modern mountain design",
    ],
    propertyDetails: {
      size: "1,200 - 2,000 sq ft",
      capacity: "4-6 people",
      bedrooms: "2-3 bedrooms",
      bathrooms: "2 bathrooms",
    },
    transportation: "Accessible by car with good road connections. Nearest airports vary by specific location. Local transportation available. 4WD recommended for some areas.",
    localCulture: "The Atlas region offers a unique mountain lifestyle with traditional culture and modern amenities. Experience authentic local traditions, mountain cuisine, and a close-knit community in a stunning natural setting.",
  },
};

// Generate static params for all locations (required for static export)
export function generateStaticParams() {
  return Object.keys(locationData).map((location) => ({
    location: location,
  }));
}
